site_name: Gökhan Özen

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: turkish
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Karanlık Tema
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
       icon: material/toggle-switch
       name: Beyaz Tema
       primary: teal
       accent: lime
       
extra:
  social:
    - icon: fontawsome/brands/github-alt
      link: https://example.com
    - icon: fontawsome/brands/twitter
      link: https://example.com
    - icon: fontawsome/brands/instagram
      link: https://example.com