site_name: Gökhan Özen

theme:
  name: material

extra:
  social:
    - icon: fontawsome/brands/github-alt
      link: https://example.com
    - icon: fontawsome/brands/twitter
      link: https://example.com
    - icon: fontawsome/brands/instagram
      link: https://example.com